services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    user: "0:0"
    ports:
      - "8085:80"
    volumes:
      - /mnt/hdd-cloud:/srv/HDD-Cloud
      - /mnt/hdd-media:/srv/HDD-Media
      - /mnt/hdd-music:/srv/HDD-Music
      - /opt/infra/filebrowser/filebrowser.db:/database/filebrowser.db
    networks:
      - shared_net

networks:
  shared_net:
    external: true
