services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    volumes:
      - /mnt/hdd-music/jellyfin/music:/media/music
      - /mnt/hdd-media/jellyfin/movies:/media/movies
      - /mnt/hdd-media/jellyfin/tv:/media/tv
      - /mnt/hdd-media/jellyfin/anime:/media/anime
      - jellyfin_config:/config
    ports:
      - "8096:8096"
    # Uncomment if hardware transcoding becomes available (Intel Quick Sync)
    # devices:
    #   - /dev/dri:/dev/dri
    networks:
      - shared_net

volumes:
  jellyfin_config:

networks:
  shared_net:
    external: true
