services:
  kavita:
    image: jvmilazz0/kavita:latest
    container_name: kavita
    restart: unless-stopped
    volumes:
      - /mnt/hdd-media/manga-reader:/manga
      - kavita_config:/kavita/config
    ports:
      - "5000:5000"
    networks:
      - shared_net

volumes:
  kavita_config:

networks:
  shared_net:
    external: true
