services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    restart: unless-stopped
    hostname: docker-host
    volumes:
      - syncthing_config:/var/syncthing/config
      - /mnt/hdd-cloud/syncthing:/var/syncthing/data
    ports:
      - "8384:8384"       # Web UI
      - "22000:22000/tcp" # Sync protocol
      - "22000:22000/udp"
      - "21027:21027/udp" # Local discovery
    networks:
      - shared_net

volumes:
  syncthing_config:

networks:
  shared_net:
    external: true
